-- Keep a log of any SQL queries you execute as you solve the mystery.
SELECT description FROM crime_scene_reports WHERE month = 7 AND day = 28 AND street = "Humphrey Street";
SELECT name, transcript FROM interviews WHERE month = 7 AND day = 28;
SELECT activity, license_plate, hour, minute FROM bakery_security_logs WHERE month = 7 AND day = 28 AND hour = 10 AND minute > 15 AND minute < 25;
SELECT account_number, amount FROM atm_transactions WHERE month = 7 AND day = 28 AND transaction_type = "withdraw" AND atm_location = "Leggett Street";
SELECT caller, receiver, duration FROM phone_calls WHERE month = 7 AND day = 28;
SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE month = 7 AND day = 28 AND transaction_type = "withdraw" AND atm_location = "Leggett Street");
SELECT name FROM people WHERE id IN (SELECT person_id FROM bank_accounts WHERE account_number IN (SELECT account_number FROM atm_transactions WHERE month = 7 AND day = 28 AND transaction_type = "withdraw" AND atm_location = "Leggett Street")) AND license_plate IN (SELECT license_plate FROM bakery_security_logs WHERE month = 7 AND day = 28 AND hour = 10 AND minute > 15 AND minute < 25) AND phone_number IN (SELECT caller FROM phone_calls WHERE month = 7 AND day = 28);
SELECT id FROM airports WHERE city = "Fiftyville";
SELECT id, hour, minute, destination_airport_id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour;
SELECT passport_number FROM people WHERE name = "Diana" or name = "Bruce";
SELECT passport_number, flight_id FROM passengers WHERE flight_id = (SELECT id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour LIMIT 1) AND passport_number IN (SELECT passport_number FROM people WHERE name = "Diana" or name = "Bruce");
SELECT name FROM people WHERE passport_number = (SELECT passport_number FROM passengers WHERE flight_id = (SELECT id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour LIMIT 1) AND passport_number IN (SELECT passport_number FROM people WHERE name = "Diana" or name = "Bruce"));
SELECT destination_airport_id FROM flights WHERE id = (SELECT id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour LIMIT 1);
SELECT city FROM airports WHERE id = (SELECT destination_airport_id FROM flights WHERE id = (SELECT id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour LIMIT 1));
SELECT phone_number FROM people WHERE passport_number = (SELECT passport_number FROM passengers WHERE flight_id = (SELECT id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour LIMIT 1) AND passport_number IN (SELECT passport_number FROM people WHERE name = "Diana" or name = "Bruce"));
SELECT receiver FROM phone_calls WHERE duration < 60 AND month = 7 AND day = 28 AND year = 2021 AND caller = (SELECT phone_number FROM people WHERE passport_number = (SELECT passport_number FROM passengers WHERE flight_id = (SELECT id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour LIMIT 1) AND passport_number IN (SELECT passport_number FROM people WHERE name = "Diana" or name = "Bruce")));
SELECT name FROM people WHERE phone_number = (SELECT receiver FROM phone_calls WHERE duration < 60 AND month = 7 AND day = 28 AND year = 2021 AND caller = (SELECT phone_number FROM people WHERE passport_number = (SELECT passport_number FROM passengers WHERE flight_id = (SELECT id FROM flights WHERE origin_airport_id = (SELECT id FROM airports WHERE city = "Fiftyville") AND day = 29 AND month = 7 AND year = 2021 ORDER BY hour LIMIT 1) AND passport_number IN (SELECT passport_number FROM people WHERE name = "Diana" or name = "Bruce"))));